### ISSUE TITLE
State of Madness card in expert mode Risky Business scenario displays all black

### ISSUE THREAD

**Issue by SwedeRacer** [funkymonkeymonk/tts-marvel-champions-automated#4] opened 2020-07-05 15:44 UTC
When using the Green Goblin "Risky Business" scenario with the expert mode enabled, the _Criminal Enterprise/State of Madness_ environment card exhibits a strange behavior. With the _Criminal Enterprise_ side showing, there is no problem, but when you flip it to the _State of Madness_ side, the card appears all black. During the flip animation, you can see the card image for a split second, but once the card is lying flat, the image is replaced by solid black.

This only happens when you check the "Include Expert Encounter Set" checkbox in the Encounter Builder. If you do not check this box, the environment card is on top of the encounter deck, and it functions normally. But if you do check the box, you have to search the encounter deck for the card, and the blackout behavior occurs. (Actually, I've just found that the only time the card works properly is when you select the _Goblin Gimmicks_ encounter set and do not check the expert mode checkbox. Using other encounter sets also causes the problem, even when not using expert mode.)

**Comment by SwedeRacer** [comment] 2020-07-05 15:50
![screenshot1](https://user-images.githubusercontent.com/13025056/86536446-f0145600-bea4-11ea-995b-4ceda154d5f6.jpg)
![screenshot2](https://user-images.githubusercontent.com/13025056/86536447-f0145600-bea4-11ea-90e8-492703c526be.jpg)

**Comment by funkymonkeymonk** [comment] 2020-07-05 17:52
Thanks for reporting. I've confirmed the bug. The reason it's black on one side is the card is marked to be hidden while face down. A short term fix that'll get you going:

1. Right-click on the card
2. Under toggles deselect "Hide face down"

This should show both sides of the card. I'll also add to my backlog of things to fix.

**Comment by SwedeRacer** [comment] 2020-07-05 18:01
Great, thanks for the info, and for all your hard work on this mod! My
friend and I use it just about every week. Do you have a Ko-fi set up, or
some other we for people to throw a little appreciation your way?

**Comment by funkymonkeymonk** [comment] 2020-07-05 19:36
Thanks for the love. I really appreciate it and please keep sending me bug reports and I'll keep working to make it better. As for Ko-fi I haven't set one up because I wouldn't want to feel like I'm making any money off of someone else's work, eg Fantasy Flight and all the other mod creators whose components I pull in. I do have some ways that you can show appreciation though.

- Send bug reports. I don't know what I don't know.
- If you don't already own the cards, please buy them. The only way this game thrives is if people buy the physical product.
- Donate to a charity that matters. https://action.aclu.org/give/now

**Comment by SwedeRacer** [comment] 2020-07-05 21:12
That's a great answer, and and a great choice for a charity! My friend and I both purchase every new release through Team Covenant's subscription service, and I just made a donation to the ACLU.

Is it appropriate to post feature or improvement ideas here, in addition to bugs?

**Comment by funkymonkeymonk** [comment] 2020-07-05 21:20
That works. I would also suggest reaching out to me on Discord. Right now much of the work that I'm doing is refactoring trying to clean up and gear up for some big changes to the way MCA works. I'm hoping to have more out before the league of cooperative gaming con end of month.

**Comment by funkymonkeymonk** [comment] 2020-07-22 05:02
Wanted to give you the heads up. I got some time to do some work this evening/morning and I've fixed the issue in a dev branch. I'm hoping to push that branch out this weekend. It includes a lot more than the fix, and I think you'll be pretty excited.

If you're interested in testing the early release branches let me know and I can add you on steam. I don't guarantee they'll work, they are early release, but it's the best way to get new features fast as well as give feedback on what's broken.

**Comment by SwedeRacer** [comment] 2020-07-22 05:10
Yeah, I'd definitely be interested in doing some testing!

**Comment by funkymonkeymonk** [comment] 2020-07-23 01:28
Cool reach out to me on discord. I'm funkymonkeymonk#4635 and I can get your steam name and add you as a playtester for the dev branch.

**Comment by funkymonkeymonk** [comment] 2020-07-26 04:07
Fix has been pushed to the workshop.

**Closed as completed by funkymonkeymonk** 2020-07-26 04:07 UTC
Labels: bug, good first issue
